version: "3"

services:
  database:
    image: postgres
    container_name: sonic_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-U", "${PGUSER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      app_network:
        ipv4_address: 10.1.0.10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "10.1.0.1:5432:5432"

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
